### ISSUE TITLE
Question About Using This

### ISSUE THREAD

**Issue by ethsmith** [bradberger/gowhmcs#1]
Could you give me an example of how to start using this? Something like an example script for adding a new client? Preferably one that would work by copy and paste or with little modification.

It would be really helpful and would give me a starting point for using this. It would also get me to the point where I could send pull requests if I add something that isn't already available with this.

**Comment by ChunkRadius** [comment]
No problem!

For a start, [here's a gist](https://gist.github.com/bradberger/74629c2a3bd1554c265bed68c8db3f9b). 

The available calls and parameters are documented on [godoc](https://godoc.org/github.com/bradberger/gowhmcs).

There's still a lot to be implemented so I'd be excited if you'd add something that you need. The basics of handling and sending responses are implemented, albeit before I didn't thoroughly understand Go interfaces at the time, so it could be done a bit cleaner in retrospect.

That being said, It is being used in production and has been pretty solid for more than a year now, and has handled a fair amount of usage in that time.

**Comment by ethsmith** [comment]
@bradberger it seems you don't have a validate login function? Shall that be my first PR then once I figure it out? :P

However if you do have a function for that and I am just missing it please let me know.

**Comment by ChunkRadius** [comment]
Sorry I missed this question until now. As mentioned on #3 unfortunately that's not implemented, but it would be a most welcome addition!
