### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ethsmith** [bradberger/gowhmcs#5]
How are you getting client details with this if I may ask? I want to make sure I am doing it right. Do you have an example script by chance?

**Comment by ChunkRadius** [comment]
Actually I don't even know that there is something set up to get client details. To date I've only used it in to create/update clients. Maybe I'm forgetting that there is something, but I don't remember/see anything right now.

**Comment by ethsmith** [comment]
@bradberger Okay thanks. I just saw the struct for ClientInfoReq and thought maybe there was a function for it.

**Comment by ChunkRadius** [comment]
Actually maybe there is and I've just forgotten about it. It's been in production for a while and I haven't revisited it until now, so maybe I've missed it. Let me check it out again and answer you more definitively...

**Comment by ethsmith** [comment]
@bradberger Any news?

**Comment by ChunkRadius** [comment]
@TekkitCommando No, there isn't anything. The only way it's been used it up until now is to check if the client exists. It wouldn't be too hard to expand on that if you wanted to, it would just be a question of marshaling the response into an appropriate struct. It's already calling the `getclientsdetails` API endpoint in `ClientExists` it's just not using the result.

**Comment by ChunkRadius** [comment]
@TekkitCommando  Adding this as a feature via #6, if you're able to submit a PR for it that would be awesome

**Comment by ethsmith** [comment]
@bradberger I can work on that this weekend possibly
